export const FETCH_ORDERS_REQUEST = "orders/FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "orders/FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILURE = "orders/FETCH_ORDERS_FAILURE";
export const SET_ORDERS_STATUS_FILTER = "orders/SET_ORDERS_STATUS_FILTER";
