export const FETCH_PAYMENTS_REQUEST = "payments/FETCH_PAYMENTS_REQUEST";
export const FETCH_PAYMENTS_SUCCESS = "payments/FETCH_PAYMENTS_SUCCESS";
export const FETCH_PAYMENTS_FAILURE = "payments/FETCH_PAYMENTS_FAILURE";

export const REFUND_PAYMENT_REQUEST = "payments/REFUND_PAYMENT_REQUEST";
export const REFUND_PAYMENT_SUCCESS = "payments/REFUND_PAYMENT_SUCCESS";
export const REFUND_PAYMENT_FAILURE = "payments/REFUND_PAYMENT_FAILURE";
