export const FETCH_REVIEWS_REQUEST = "reviews/FETCH_REVIEWS_REQUEST";
export const FETCH_REVIEWS_SUCCESS = "reviews/FETCH_REVIEWS_SUCCESS";
export const FETCH_REVIEWS_FAILURE = "reviews/FETCH_REVIEWS_FAILURE";
export const SET_REVIEWS_STATUS_FILTER = "reviews/SET_REVIEWS_STATUS_FILTER";
export const MODERATE_REVIEW_REQUEST = "reviews/MODERATE_REVIEW_REQUEST";
export const MODERATE_REVIEW_SUCCESS = "reviews/MODERATE_REVIEW_SUCCESS";
export const MODERATE_REVIEW_FAILURE = "reviews/MODERATE_REVIEW_FAILURE";
