export const FETCH_SETTINGS_REQUEST = "settings/FETCH_SETTINGS_REQUEST";
export const FETCH_SETTINGS_SUCCESS = "settings/FETCH_SETTINGS_SUCCESS";
export const FETCH_SETTINGS_FAILURE = "settings/FETCH_SETTINGS_FAILURE";
export const SAVE_SETTINGS_REQUEST = "settings/SAVE_SETTINGS_REQUEST";
export const SAVE_SETTINGS_SUCCESS = "settings/SAVE_SETTINGS_SUCCESS";
export const SAVE_SETTINGS_FAILURE = "settings/SAVE_SETTINGS_FAILURE";
